# Generated by Django 3.0.8 on 2020-07-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicApp', '0006_auto_20200712_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Read more...', max_length=255),
        ),
    ]
