# Generated by Django 3.1 on 2020-08-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicApp', '0017_auto_20200806_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, default='sassa', null=True, upload_to='images/'),
        ),
    ]
